# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10GSz1hrJKm0hbmEX8s-26hkVszTZz86d
"""

import pandas as pd
import sklearn as skl
import numpy as np

from google.colab import files
upoloaded = files.upload()

import pandas as pd
path = "heart.csv"
df = pd.read_csv(path)

df.head()

df.isnull().sum()

df.corr()

X = df[['cp', 'thalach','fbs','restecg','slope']]
Y = df["target"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, Y, test_size=0.3)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

from sklearn.neighbors import KNeighborsClassifier
k = 5
neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
neigh

yhat = neigh.predict(X_test)

from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, neigh.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat))

