# -*- coding: utf-8 -*-
"""Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GfgETmccDn59yBl4U9ljMi-Ebu5HKnXK
"""

from google.colab import files
upoloaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import pandas as pd
path = "height and weight.csv"
df = pd.read_csv(path)
df.head(5)

from sklearn.linear_model import LinearRegression

lm = LinearRegression()
lm

X = df[['Height']]
Y = df['Weight']

lm.fit(X,Y)

T=[[7]]
Yhat = lm.predict(X)
Yhat

lm.intercept_

lm.coef_

from sklearn.metrics import mean_squared_error

a = mean_squared_error(Y,Yhat)
print(a)

a = np.sum(X)

np.mean(a)

b = np.sum(Y)

np.mean(b)

