# -*- coding: utf-8 -*-
"""Regression2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RxbbDR-cxCVACwApYioNcUR3gGfhRR6b
"""

from google.colab import files
upoloaded = files.upload()

import pandas as pd
path = "Realestate.csv"
df = pd.read_csv(path)
df.head()

df.corr()

X = df[['inp1','inp2','inp3','inp4']]
Y = df[['output']]

from sklearn.linear_model import LinearRegression

lm = LinearRegression()
lm

lm.fit(X,Y)

lm.intercept_

lm.coef_

from sklearn.metrics import mean_squared_error
Yhat = lm.predict(X)
Yhat

a = mean_squared_error(Y,Yhat)
print(a)